DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  oauth_id TEXT UNIQUE NOT NULL,
  requests INTEGER DEFAULT 0,
  reset_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);